# Generated by Django 3.1.7 on 2021-05-25 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='pic')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('zip_code', models.CharField(max_length=30)),
                ('clinic_name', models.CharField(blank=True, max_length=50, null=True)),
                ('clinic_address', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_timing', models.CharField(blank=True, max_length=30, null=True)),
                ('clinic_city_name', models.CharField(blank=True, max_length=30, null=True)),
                ('consultancy_fees', models.IntegerField(blank=True, null=True)),
                ('services', models.CharField(blank=True, max_length=50, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('pro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
