# Generated by Django 3.1.7 on 2021-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0002_auto_20210526_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilee',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profilee',
            name='country',
            field=models.CharField(default='India', max_length=40),
        ),
        migrations.AlterField(
            model_name='profilee',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
