# Generated by Django 3.1.7 on 2021-06-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module1', '0003_auto_20210605_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilee',
            old_name='consultancy_fees',
            new_name='first_time_consultFees',
        ),
        migrations.RemoveField(
            model_name='profilee',
            name='clinic_timing',
        ),
        migrations.RemoveField(
            model_name='profilee',
            name='services',
        ),
        migrations.AddField(
            model_name='profilee',
            name='clinic_contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilee',
            name='clinic_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilee',
            name='clinic_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilee',
            name='second_time_consultFees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilee',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
